### ISSUE TITLE
DMR: Technical Design

### ISSUE THREAD

**Issue by shelabd** [buerokratt/DMR.NET#2]
AS A Developer
I WANT a technical design covering all the components, technologies, platforms and programming languages used within a project
SO THAT I would have a clear understanding of the technical stack within which I can operate

- [ ] Client requests to Chatbot
- [ ] Chatbots
- [ ] CentOps
- [ ] DMR
- [ ] Classifier
- [ ] CI
- [ ] CD

**Comment by turnerrainer** [comment]
Was merged to `main` branch as an initial draft to keep working on.
