### ISSUE TITLE
DMR: NGINX Spike

### ISSUE THREAD

**Issue by martinkearn** [buerokratt/DMR.NET#24]
AS A engineer
I WANT to understand better Rainer's vision for how NGINX can be used for DMR's dumb pipe
SO THAT I can see how DMR fits into the overall architecture

A working spike (quick throw-away code/config, no tests, no PR etc) to showcase how NGINX can be used to do the routing required for DMR in the context of the overall Burokratt solution.

Goal is that team is comfortable moving forward with NGINX.

## Acceptance Criteria

- [x] Work out mapping between ministry and bot forward URL
- [x] A demo on how the mapping table gets updated
- [x] How DMR handles when classifier service is not available. Switch classifier off and ensure messages are not dropped (see @tonistuulNG comment below)

**Comment by tonistuulNG** [comment]
What happens when:
1. Bot sends message to DMR
2. DMR responds with 202
3. DMR tries to send message to Classifier, but network is now failing / Classifier is not working
Do we lose the message?

**Comment by shelabd** [comment]
To be split for this sprint and next sprint

**Comment by turnerrainer** [comment]
### Use different backends based on headers
https://sites.psu.edu/jasonheffner/2015/06/19/nginx-use-different-backend-based-on-http-header/

**Comment by turnerrainer** [comment]
### Accept POST requests
By default, Nginx accepts GET requests. A quick hack to allow POST requests as well is as following:
```
server {
    # ...

    error_page  405     =200 $uri;

    # ...
}
```

**Comment by turnerrainer** [comment]
### Load balancing
In case we have 5k participants and mapping them within 1 Nginx conf is not an option, load balancing comes to play. See https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/ for more.

**Comment by turnerrainer** [comment]
More from https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/

### Down for maintainance
_"If one of the servers needs to be temporarily removed from the load‑balancing rotation, it can be marked with the [down](https://nginx.org/en/docs/http/ngx_http_upstream_module.html#down) parameter in order to preserve the current hashing of client IP addresses. Requests that were to be processed by this server are automatically sent to the next server in the group:"_

```
upstream backend {
    server backend1.example.com;
    server backend2.example.com;
    server backend3.example.com down;
}
```
### Using server weights
_"By default, NGINX distributes requests among the servers in the group according to their weights using the Round Robin method. The [weight](https://nginx.org/en/docs/http/ngx_http_upstream_module.html#weight) parameter to the [server](https://nginx.org/en/docs/http/ngx_http_upstream_module.html#server) directive sets the weight of a server; the default is 1."_

```
upstream backend {
    server backend1.example.com weight=5;
    server backend2.example.com;
    server 192.0.0.1 backup;
}
```

**Comment by turnerrainer** [comment]
### Define a fallback server
- Report errors;
- Respond to participant that made the initial request.

https://serverfault.com/questions/765483/how-to-add-a-fallback-to-my-proxy-in-nginx

**Comment by turnerrainer** [comment]
### Define `max_fails` and `fail_timeout` and a fallback
http://nginx.org/en/docs/http/ngx_http_upstream_module.html#upstream

```
upstream backend {
    server backend1.example.com weight=5;
    server 127.0.0.1:8080       max_fails=3 fail_timeout=30s;
    server unix:/tmp/backend3;

    server backup1.example.com  backup;
}
```
_"By default, requests are distributed between the servers using a weighted round-robin balancing method. In the above example, each 7 requests will be distributed as follows: 5 requests go to backend1.example.com and one request to each of the second and third servers. If an error occurs during communication with a server, the request will be passed to the next server, and so on until all of the functioning servers will be tried. If a successful response could not be obtained from any of the servers, the client will receive the result of the communication with the last server."_

**Comment by turnerrainer** [comment]
1. Use `docker cp` command to transfer files from CentOps to DMRs. See https://docs.docker.com/engine/reference/commandline/cp/ for more.
2. Reload Nginx container with `docker exec <CONTAINER NAME> nginx -s reload` for changes to take effect.

**Comment by decodingahmed** [comment]
Spike is done here: https://github.com/buerokratt/DMR-Nginx
