### ISSUE TITLE
DMR: Setup CI

### ISSUE THREAD

**Issue by shelabd** [buerokratt/DMR.NET#3]
AS A Developer
I WANT TO be sure my changes can be built, and tests pass when merged with the main branch
SO THAT the main branch is always functioning and 'shippable'.

### Acceptance Criteria
- [ ] Create Github actions which build and test the code in the DMR repo

Depends on https://github.com/buerokratt/Cross-functional-requirements/issues/18

**Comment by LNOXS07** [comment]
@keijoraamat dependent on documentation task.

**Comment by martinkearn** [comment]
Done as part of another task
