### ISSUE TITLE
DMR: Publish DMR client Nuget package

### ISSUE THREAD

**Issue by martinkearn** [buerokratt/DMR.NET#30]
AS A Burokratt developer
I WANT to use a package/library for interacting with DMR
SO THAT the way that all components interact with DMR is consistent and separated out from the code of the component

Take the `DMRService` that already exists and extract that out to a separate project in the DMR repository.

Publish as a Nuget package which all components can use

## Acceptance Criteria

- [x] Work out a versioning scheme - @priyankasharma55 
- [x] Work out where to publish the package (Nuget or GitHub) - @priyankasharma55 
- [x] Identify where to store the code. Its own repo or part of DMR repo? - @joonasroosalung 

## Split issues
- buerokratt/Request-Processor#3 
- buerokratt/Request-Processor#1 
- buerokratt/Request-Processor#2
- buerokratt/Request-Processor#5

**Comment by martinkearn** [comment]
@decodingahmed .... this is one that still needs refinement and grooming but a potential good next task for you? The Mock Bot project will soon need this as well as Mock Classifier.

**Comment by martinkearn** [comment]
We discussed de-prioritising this given that both the places where this is used are just mocks so copying code is not the end of the world

**Comment by martinkearn** [comment]
Putting back on the grooming list so we can re-consider the priority as a group

**Comment by martinkearn** [comment]
Distribute work between @martinkearn and @joonasroosalung and @priyankasharma55

**Comment by martinkearn** [comment]
Potentially useful resources:
- https://github.com/guypritchard/simple-versioning-middleware/blob/master/.github/workflows/publish.yml
- https://github.com/martinkearn/Nuget-test

**Comment by joonasroosalung** [comment]
Code will be stored in its own repo. Package name, project name, namespace TBD...

**Comment by joonasroosalung** [comment]
Keijo will create NuGet account to upload package to

**Comment by priyankasharma55** [comment]
Keijo has created API key for NuGet Gallery and added to GitHub Secrets under NUGET_GALLERY_API_KEY.

**Comment by joonasroosalung** [comment]
Split new issues for myself from acceptance criteria
- buerokratt/Request-Processor#3 
- buerokratt/Request-Processor#1 
- buerokratt/Request-Processor#2

**Comment by priyankasharma55** [comment]
Nuget package available in Nuget Gallery : https://www.nuget.org/packages/RequestProcessor
