### ISSUE TITLE
DMR: Implement DMR Routing Capability with .NET

### ISSUE THREAD

**Issue by guypritchard** [buerokratt/DMR.NET#32]
AS A Paticipant in the Buerokratt system
I WANT A common location to send messages to allow them to be classified and routed to the correct chatbot
SO THAT user inquiries can be resolved by the correct respondent.

> Note.  CentOps is yet to be implemented so CentOps responses will be handled by configuration rather than API Calls.

## Acceptance Criteria
- [x] Implement Routing and API as Per Open API Spec and Specification Documents
- [x] Unit tested
- [x] Packaged as a Docker Container
- [x] Implementation Documented
- [x] Demo-ed to Team

**Comment by shelabd** [comment]
Revise after change in API design
