### ISSUE TITLE
DMR: Replicate DMR functionality with NGINX

### ISSUE THREAD

**Issue by shelabd** [buerokratt/DMR.NET#39]
As an ARCHITECT
I WANT to have a version of DMR running on NGINX 
SO that I can evaluate feature parity

### Acceptance Criteria

- [x] accept messages and custom headers at /messages endpoint, return 202 immediately
- [x] redirect message according to X-Send-To header (currently only to Classifier and url hardcoded)
- [x] send an error message to X-Sent-By if X-Send-To is not available

**Comment by shelabd** [comment]
Attempt to replicate .NET functionality will assess at the end of the sprint of feasibility

**Comment by turnerrainer** [comment]
In AC, "error payload base64 encoded" in unnecessary. Nginx will not encrypt (or ancode64 at this point) any of its messages.

Custom header to represent "Unable to send message" with initial message headers should be appropriate.

**Comment by tonistuulNG** [comment]
carried over to next sprint as https://github.com/buerokratt/DMR/issues/42

**Comment by decodingahmed** [comment]
Delivered across 2 issues.
