### ISSUE TITLE
DMR: CentOps-to-NGINX converter [spike]

### ISSUE THREAD

**Issue by shelabd** [buerokratt/DMR.NET#40]
AS AN Architect
I WANT to have a component between CentOps and DMR which presents CentOps information in NGINX format
SO THAT I can ensure that no changes are needed on CentOps if NGINX is used for DMR

**This is a spike.**

The current DMR is built in .net which has the capability to make a request to CentOps to get the latest information about participant status.

If DMR is implemented in NGINX, we cannot make these requests because NGINX is just a "dump pipe" router. Instead, NGINX will rely on its routing tables being proactively updated to reflect the latest status from CentOps.

This component is a service that sits between CentOps and DMR (on NGINX) and routinely gets the latest status information from CentOps, converts it to the format required by NGINX and publishes it to NGINX.

This component is only required to facilitate DMR running on NGINX. The .net DMR does not need this component.

The objective of the spike is to experiment with how such a component could be built and inform the final technical design.

This has a dependency on a running NGINX platform

## Acceptance Criteria

- [x] Document the objectives for the spike
- [x] Document the high level technical approach for the spike
- [x] Demonstrate working component to team

**Comment by shelabd** [comment]
Demonstration will be on the terminal

**Comment by tonistuulNG** [comment]
https://github.com/buerokratt/DMR-Nginx/pull/2
